// <auto-generated />
using System;
using Backend.SQLDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(SQLServerDbContext))]
    partial class SQLServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Model.Entity.Administrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Administrator_Status");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Administrator_Username")
                        .HasFilter("Status = 1");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("Backend.Model.Entity.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Option")
                        .HasDatabaseName("IX_Cart_Option");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId", "Option")
                        .IsUnique()
                        .HasDatabaseName("IX_Cart_CustomerId_ProductId_Option");

                    b.ToTable("Carts", t =>
                        {
                            t.HasCheckConstraint("CK_Cart_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Backend.Model.Entity.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Category_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Category_Slug");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Backend.Model.Entity.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AvtURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerName")
                        .HasDatabaseName("IX_Customer_CustomerName");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Customer_Email");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_Customer_PhoneNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Customer_Status");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Backend.Model.Entity.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Invoice_CreatedAt");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Invoice_CustomerId");

                    b.HasIndex("ReceiverPhone")
                        .HasDatabaseName("IX_Invoice_ReceiverPhone");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Invoice_Status");

                    b.HasIndex("TrackingCode")
                        .HasDatabaseName("IX_Invoice_TrackingCode");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Backend.Model.Entity.InvoiceDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("ShipmentBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("VariantSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShipmentBatchId");

                    b.HasIndex("VariantSlug")
                        .HasDatabaseName("IX_InvoiceDetail_Option");

                    b.HasIndex("InvoiceId", "ProductId")
                        .HasDatabaseName("IX_InvoiceDetail_InvoiceId_ProductId");

                    b.ToTable("InvoiceDetails", t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceDetail_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Backend.Model.Entity.InvoiceStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_InvoiceStatusHistory_CreatedAt");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("IX_InvoiceStatusHistory_InvoiceId");

                    b.ToTable("InvoiceStatusHistories");
                });

            modelBuilder.Entity("Backend.Model.Entity.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("SubCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId")
                        .HasDatabaseName("IX_Product_SubCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Backend.Model.Entity.ProductDailyStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("ViewsCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_ProductDailyStat_Date");

                    b.HasIndex("ProductId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductDailyStat_ProductId_Date");

                    b.ToTable("ProductDailyStats", t =>
                        {
                            t.HasCheckConstraint("CK_ProductDailyStat_ViewsCount_NonNegative", "[ViewsCount] >= 0");
                        });
                });

            modelBuilder.Entity("Backend.Model.Entity.RecentlyView", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_RecentlyView_CustomerId_ProductId");

                    b.HasIndex("CustomerId", "ViewedAt")
                        .HasDatabaseName("IX_RecentlyView_CustomerId_ViewedAt");

                    b.ToTable("RecentlyViews");
                });

            modelBuilder.Entity("Backend.Model.Entity.ShipmentBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ImportPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportedQuantity")
                        .HasColumnType("int");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<string>("VariantSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BatchCode")
                        .IsUnique()
                        .HasDatabaseName("IX_ShipmentBatch_BatchCode");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ShipmentBatch_ProductId");

                    b.ToTable("ShipmentBatches");
                });

            modelBuilder.Entity("Backend.Model.Entity.SubCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_SubCategory_Name");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_SubCategory_CategoryId_Name");

                    b.HasIndex("CategoryId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_SubCategory_CategoryId_Slug");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("Backend.Model.Entity.VNPayPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasDatabaseName("IX_VNPayPayment_InvoiceId");

                    b.HasIndex("TransactionCode")
                        .IsUnique()
                        .HasDatabaseName("IX_VNPayPayment_TransactionCode");

                    b.ToTable("VNPayPayments");
                });

            modelBuilder.Entity("Backend.Model.Entity.Cart", b =>
                {
                    b.HasOne("Backend.Model.Entity.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entity.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Model.Entity.Customer", b =>
                {
                    b.OwnsOne("Backend.Model.Entity.ShippingAddress", "StandardShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DetailAddress")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("StandardShippingAddress_DetailAddress");

                            b1.Property<int>("DistrictId")
                                .HasColumnType("int")
                                .HasColumnName("StandardShippingAddress_DistrictId");

                            b1.Property<string>("DistrictName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("StandardShippingAddress_DistrictName");

                            b1.Property<string>("DistrictValue")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("StandardShippingAddress_DistrictValue");

                            b1.Property<string>("ProvinceCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("StandardShippingAddress_ProvinceCode");

                            b1.Property<int>("ProvinceId")
                                .HasColumnType("int")
                                .HasColumnName("StandardShippingAddress_ProvinceId");

                            b1.Property<string>("ProvinceName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("StandardShippingAddress_ProvinceName");

                            b1.Property<int>("WardsId")
                                .HasColumnType("int")
                                .HasColumnName("StandardShippingAddress_WardsId");

                            b1.Property<string>("WardsName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("StandardShippingAddress_WardsName");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("StandardShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Model.Entity.Invoice", b =>
                {
                    b.HasOne("Backend.Model.Entity.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Backend.Model.Entity.ShippingAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<long>("InvoiceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("DetailAddress")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShippingAddress_DetailAddress");

                            b1.Property<int>("DistrictId")
                                .HasColumnType("int")
                                .HasColumnName("ShippingAddress_DistrictId");

                            b1.Property<string>("DistrictName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShippingAddress_DistrictName");

                            b1.Property<string>("DistrictValue")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShippingAddress_DistrictValue");

                            b1.Property<string>("ProvinceCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShippingAddress_ProvinceCode");

                            b1.Property<int>("ProvinceId")
                                .HasColumnType("int")
                                .HasColumnName("ShippingAddress_ProvinceId");

                            b1.Property<string>("ProvinceName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShippingAddress_ProvinceName");

                            b1.Property<int>("WardsId")
                                .HasColumnType("int")
                                .HasColumnName("ShippingAddress_WardsId");

                            b1.Property<string>("WardsName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ShippingAddress_WardsName");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Model.Entity.InvoiceDetail", b =>
                {
                    b.HasOne("Backend.Model.Entity.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entity.Product", "Product")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entity.ShipmentBatch", "ShipmentBatch")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ShipmentBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");

                    b.Navigation("ShipmentBatch");
                });

            modelBuilder.Entity("Backend.Model.Entity.InvoiceStatusHistory", b =>
                {
                    b.HasOne("Backend.Model.Entity.Invoice", "Invoice")
                        .WithMany("StatusHistories")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Backend.Model.Entity.Product", b =>
                {
                    b.HasOne("Backend.Model.Entity.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Backend.Model.Entity.ProductDailyStat", b =>
                {
                    b.HasOne("Backend.Model.Entity.Product", "Product")
                        .WithMany("ProductDailyStats")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Model.Entity.RecentlyView", b =>
                {
                    b.HasOne("Backend.Model.Entity.Customer", "Customer")
                        .WithMany("RecentlyViews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Entity.Product", "Product")
                        .WithMany("RecentlyViews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Model.Entity.ShipmentBatch", b =>
                {
                    b.HasOne("Backend.Model.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Model.Entity.SubCategory", b =>
                {
                    b.HasOne("Backend.Model.Entity.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Model.Entity.VNPayPayment", b =>
                {
                    b.HasOne("Backend.Model.Entity.Invoice", "Invoice")
                        .WithOne("VNPayPayment")
                        .HasForeignKey("Backend.Model.Entity.VNPayPayment", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Backend.Model.Entity.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Backend.Model.Entity.Customer", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Invoices");

                    b.Navigation("RecentlyViews");
                });

            modelBuilder.Entity("Backend.Model.Entity.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("StatusHistories");

                    b.Navigation("VNPayPayment");
                });

            modelBuilder.Entity("Backend.Model.Entity.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("InvoiceDetails");

                    b.Navigation("ProductDailyStats");

                    b.Navigation("RecentlyViews");
                });

            modelBuilder.Entity("Backend.Model.Entity.ShipmentBatch", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("Backend.Model.Entity.SubCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
